ignored = ["github.com/libp2p/go-libp2p-crypto"]

[[constraint]]
  name = "github.com/RTradeLtd/config"
  branch = "master"

[[constraint]]
  name = "github.com/RTradeLtd/grpc"
  version = "1.0.6"

[[constraint]]
  name = "github.com/RTradeLtd/rtfs"
  branch = "ungx-clean"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[prune]
  go-tests = true
  unused-packages = true
