[[constraint]]
  name = "github.com/RTradeLtd/config"
  version = "~v2.0.0"

[[constraint]]
  name = "github.com/RTradeLtd/grpc"
  branch = "master"

[[constraint]]
  name = "github.com/RTradeLtd/rtfs"
  version = "~v2.0.0"

[prune]
  go-tests = true
  unused-packages = true
