[[constraint]]
  name = "github.com/RTradeLtd/config"
  branch = "master"

[[constraint]]
  name = "github.com/RTradeLtd/grpc"
  branch = "krab/delete"

[[constraint]]
  name = "github.com/RTrade/krab"
  branch = "prod-prep"

[[constraint]]
  name = "github.com/RTradeLtd/rtfs"
  branch = "master"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[prune]
  go-tests = true
  unused-packages = true
